name: Deploy bakehouse via GitHub actions

on:
  push:
    branches: [bakehouse-deploy]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  setup:
    name: Setup for deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect environment
        id: detect-env
        run: |
          BRANCH_NAME="${{ github.ref }}"
          if [[ "${BRANCH_NAME}" == "refs/heads/main" ]]; then
              ENV="staging"
              ACCOUNT="827602716979"
          else
              ENV="dev"
              ACCOUNT="827602716979"
          fi
          echo "environment=${ENV}" >> $GITHUB_OUTPUT
          echo "account=${ACCOUNT}" >> $GITHUB_OUTPUT

      - name: Add environment variables
        run: |
          BAKEHOUSE_STACK_NAME=${{ secrets.BAKEHOUSE_STACK_NAME }}

      - name: Install dependencies
        run: |
          bash ./install.sh
      
      # run unit tests

  aws-configure:
    name: Configure AWS
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Additional steps
        run: |
          # Your commands that require AWS credentials
          echo "aws-arn=aws sts get-caller-identity --query Arn --output text" >> $GITHUB_ENV
          if [[ "${aws-arn}" -ne *"${{ vars.EXPECTED_ARN_NAME }}"* ]]; then
            echo "❌ AWS configure failed!"
            exit 1
          fi
